### PR TITLE
Switch to Jetpack Compose instead of xml for layouts

### LINKED ISSUE #37: Dark mode

### LINKED ISSUE #56: Bottom bar still overlaps main view sometimes
The last two cards in are never fully visible, but are partially hidden by the player

### LINKED ISSUE #78: Provide placeholder for server url on login view
A user is warned when they didn't provide a correct url, but is not told what a correct url looks like.
Maybe we should provide a placeholder to tell them?

IMHO we also shouldn't require the user to type `https://`, since this will/should always be the case

### LINKED ISSUE #186: Migrate to Jetpack Compose

### PR DESCRIPTION
**Pull request by chvp**
Login before:
Screenshot_20210716-160558_Accentor

Login after:
Screenshot_20210716-205925_Accentor
Screenshot_20210716-205935_Accentor

 

Fixes #186 
Fixes #37 
Fixes #78.
Fixes #56.

### CODE REVIEW

**Comment by robbevp** [comment]
Some suggestions/nitpicks
* add some top margin to form, to better use the empty space
* align submit button to right (and slightly more margin than between the inputs
* add accents in secundary color (though that might be better used in focus/active states).
* i would try a darker blue in dark mode. I personally don't like the blue with black text (though i guess it provides better contrast than that blue with white). The button would be more prominent if we could use white text.
* font looks a bit small, but that is probably because I'm looking at a screenshot on my phone

**Comment by chvp** [comment]
* Usually the keyboard is raised in this view, which makes the empty space a lot less noticeable, but I'll look into it.
* I'll take a look at what other apps do for this, but I like it in the middle, personally.
* Right, when I was working on this I assumed that the Material library I'm using would do this, but it seems like the default is primary everywhere, so I guess it's up to the developer to pick where secondary should be used instead. I'll definitely do it for the focus, not sure about the button.
* The shades are those [recommended by the material design spec](https://material.io/design/color/dark-theme.html#ui-application). I was a little hesitant at first as well, but I got used to it pretty quickly.
* Font size is probably because I configure my phone to show (very) small font sizes.

**Comment by robbevp** [comment]
>     * Usually the keyboard is raised in this view, which makes the empty space a lot less noticeable, but I'll look into it.

Didn't think about this. Makes it less of an issue (esp if there is an equivalent to the autofocus attribute, so that the keyboard drawer is open immediately)


>     * The shades are those [recommended by the material design spec](https://material.io/design/color/dark-theme.html#ui-application). I was a little hesitant at first as well, but I got used to it pretty quickly.

I don't see this color light blue/black text combination on the page you linked. My issue isn't so much with the black text, as with that color combination. I like the purple or teal that is used in the examples better.

**Comment by chvp** [comment]
> I don't see this color light blue/black text combination on the page you linked. My issue isn't so much with the black text, as with that color combination. I like the purple or teal that is used in the examples better.

The exact combination isn't there, but the general idea is to use the 200 variant of the primary color. (Which in our case is the blue from the 2014 material design color palette.)

**Comment by chvp** [comment]
Note to self:
 * Put player views back in
 * Fix Intent (also notificationbuilder)
 * Fix back to close player
 * Fix switch to LoginActivity if not logged in
 * Remove Glide from gradle and MusicService

**Comment by chvp** [comment]
New album views:
Screenshot_20210718-155240_Accentor
Screenshot_20210718-155251_Accentor

**Comment by chvp** [comment]
New artists view:
Screenshot_20210718-155450_Accentor
Screenshot_20210718-155437_Accentor

**Pull request merged**
